server:
  port: ${SERVER-PORT:8080}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA-SERVER:http://localhost:8761/eureka}

spring:
  application:
    name: user-microservice
  datasource:
    url: jdbc:postgresql://${PG-HOST:localhost}:${PG-PORT:5432}/${PG-BASE:task-tide}
    username: ${PG-USER:postgres}
    password: ${PG-PASS:1234567}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
task-tide:
  security:
    secret-key: ${SECRET-KEY:developer}

