server:
  port: 9010
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA-SERVER:http://localhost:8761/eureka}
spring:
  application:
    name: bff-scheduler-microservice
