server:
  port: ${SERVER-PORT:8080}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA-SERVER:http://localhost:8761/eureka}
spring:
  application:
    name: notifications-microservice
  thymeleaf:
    enabled: true
  sendgrid:
    api-key: ${SEND-GRID-API-KEY:null}
  profiles:
    active: ${CURRENT-PROFILE:test}
task-tide:
  email-sender:
    from: ${EMAIL-SENDER-FROM:test@test.com}
    friendly-name: ${EMAIL-SENDER-FRIENDLY-NAME:developer}