name: PR Workflow

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
        
      - name: Grant execute permission for gradlew in User
        run: cd user/ && chmod +x gradlew

      - name: Build with Gradle in User
        run: cd user/ && ./gradlew build

      - name: Run tests in User
        run: cd user/ && ./gradlew test

      - name: Grant execute permission for gradlew in Task-Scheduler
        run: cd task-scheduler/ && chmod +x gradlew

      - name: Build with Gradle in Task-Scheduler
        run: cd task-scheduler/ && ./gradlew build

      - name: Run tests in Task-Scheduler
        run: cd task-scheduler/ && ./gradlew test

      - name: Grant execute permission for gradlew in Notifications
        run: cd notifications/ && chmod +x gradlew

      - name: Build with Gradle in Notifications
        run: cd notifications/ && ./gradlew build

      - name: Run tests in Notifications
        run: cd notifications/ && ./gradlew test

      - name: Grant execute permission for gradlew in BFF Scheduling
        run: cd bff-scheduler/ && chmod +x gradlew

      - name: Build with Gradle in BFF Scheduling
        run: cd bff-scheduler/ && ./gradlew build

      - name: Run tests in BFF Scheduling
        run: cd bff-scheduler/ && ./gradlew test

      - name: Grant execute permission for gradlew in Naming Service
        run: cd naming-server/ && chmod +x gradlew

      - name: Build with Gradle in BFF Scheduling
        run: cd naming-server/ && ./gradlew build

      - name: Run tests in BFF Scheduling
        run: cd naming-server/ && ./gradlew test