server:
  port: 8090
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA-SERVER:http://localhost:8761/eureka}
spring:
  application:
    name: task-scheduler-microservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/task-tide
task-tide:
  security:
    secret-key: ${SECRET-KEY:developer}
