server:
  port: ${SERVER-PORT:8080}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA-SERVER:http://localhost:8761/eureka}
spring:
  application:
    name: task-scheduler-microservice
  data:
    mongodb:
      uri: mongodb://${MONGODB-HOST:localhost}:${MONGODB-PORT:27017}/${MONGODB-BASE:task-tide}
task-tide:
  security:
    secret-key: ${SECRET-KEY:developer}
